import WebSocket from 'ws';
import { CognitoIdentityClient, GetCredentialsForIdentityCommand, GetIdCommand } from '@aws-sdk/client-cognito-identity';
import { SignatureV4 } from '@smithy/signature-v4';
import { HttpRequest } from '@smithy/protocol-http';
import { Sha256 } from '@aws-crypto/sha256-js';

const REGION='ap-east-1', POOL='ap-east-1:94175a79-f33f-48c1-89f3-fc79288207f0';
const ENDPOINT='a36ytt8gq852xf-ats.iot.ap-east-1.amazonaws.com';
const cog=new CognitoIdentityClient({region:REGION});
const id=(await cog.send(new GetIdCommand({IdentityPoolId:POOL}))).IdentityId;
const c=(await cog.send(new GetCredentialsForIdentityCommand({IdentityId:id}))).Credentials;
const sessionToken=c.SessionToken;
const signer=new SignatureV4({credentials:{accessKeyId:c.AccessKeyId,secretAccessKey:c.SecretKey},region:REGION,service:'iotdevicegateway',sha256:Sha256});
const req=new HttpRequest({protocol:'wss:',hostname:ENDPOINT,path:'/mqtt',method:'GET',headers:{host:ENDPOINT}});
const presigned=await signer.presign(req,{expiresIn:3600});
const qs=new URLSearchParams(presigned.query).toString();
const url=`wss://${ENDPOINT}${presigned.path}?${qs}&X-Amz-Security-Token=${encodeURIComponent(sessionToken)}`;
console.log('URL length', url.length);
const ws = new WebSocket(url, ['mqtt']);
ws.on('open', () => { console.log('✅ ws open'); ws.close(); });
ws.on('error', (e) => { console.log('❌ ws error:', e.message); });
ws.on('close', (code, reason) => { console.log('close code', code, 'reason:', reason?.toString()); process.exit(0); });
setTimeout(() => { console.log('TIMEOUT'); process.exit(2); }, 6000);
